import { MainFooter } from "@/components/MainFooter";
import MainNavBar from "@/components/MainNavBar";
import type { LayoutParams } from "@/types/next";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutParams) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <Providers>
          <div className="font-[family-name:var(--font-geist-sans)]" style={{height: "calc(100% - 64px)"}}>
            <MainNavBar />
            <main className="flex pt-4 justify-center mb-16">
              {children}
            </main>
            <MainFooter />
          </div>
        </Providers>
      </body>
    </html>
  );
}
